from pathlib import Path

import torch
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline


AUDIO_DIR = Path("audio")
MODEL_NAME = "openai/whisper-base"


def get_latest_original(device_id):
    files = sorted(
        AUDIO_DIR.glob(f"mic_device_{device_id}_*.wav")
    )

    # IMPORTANT:
    # Exclude files generated by the audio preprocessor.
    originals = [
        f for f in files
        if not f.stem.endswith("_clean")
    ]

    return originals[-1] if originals else None


def get_latest_cleaned(device_id):
    files = sorted(
        AUDIO_DIR.glob(f"mic_device_{device_id}_*_clean.wav")
    )

    return files[-1] if files else None


def load_whisper():
    print("\n===== LOADING LOCAL WHISPER =====")
    print(f"Model: {MODEL_NAME}")

    use_cuda = torch.cuda.is_available()
    device = 0 if use_cuda else -1
    dtype = torch.float16 if use_cuda else torch.float32

    if use_cuda:
        print(f"GPU: {torch.cuda.get_device_name(0)}")
    else:
        print("GPU unavailable. Using CPU.")

    processor = AutoProcessor.from_pretrained(MODEL_NAME)

    model = AutoModelForSpeechSeq2Seq.from_pretrained(
        MODEL_NAME,
        torch_dtype=dtype,
    )

    speech_pipeline = pipeline(
        "automatic-speech-recognition",
        model=model,
        tokenizer=processor.tokenizer,
        feature_extractor=processor.feature_extractor,
        torch_dtype=dtype,
        device=device,
    )

    print("Whisper loaded.")
    return speech_pipeline


def transcribe(whisper, audio_path):
    result = whisper(
        str(audio_path),
        generate_kwargs={
            "task": "transcribe",
            "language": "en",
            "temperature": 0,
            "num_beams": 5,
            "condition_on_prev_tokens": False,
        },
    )

    text = result.get("text", "").strip()

    return text if text else "[NO TRANSCRIPTION]"


def main():
    print("===== AEGIS ORIGINAL VS CLEAN AUDIO TEST =====")

    test_files = []

    for device_id in (1, 11):
        original = get_latest_original(device_id)
        cleaned = get_latest_cleaned(device_id)

        print(f"\nDevice {device_id}")

        if original:
            print(f"Original: {original}")
            test_files.append(
                (f"Device {device_id} - ORIGINAL", original)
            )
        else:
            print("Original: NOT FOUND")

        if cleaned:
            print(f"Cleaned : {cleaned}")
            test_files.append(
                (f"Device {device_id} - CLEANED", cleaned)
            )
        else:
            print("Cleaned : NOT FOUND")

    if not test_files:
        print("\nNo recordings found.")
        return

    whisper = load_whisper()

    print("\n===== TRANSCRIPTION RESULTS =====")

    for label, audio_path in test_files:
        print(f"\n--- {label} ---")
        print(f"File: {audio_path}")

        try:
            transcript = transcribe(
                whisper,
                audio_path,
            )

            print(f"Transcript: {transcript}")

        except Exception as exc:
            print(
                f"Transcription failed: "
                f"{type(exc).__name__}: {exc}"
            )

    print("\n===== A/B TEST COMPLETE =====")
    print("\nExpected sentence:")
    print("This is an Aegis microphone test.")


if __name__ == "__main__":
    main()